title: 'Course #1 - What makes a good public speaker?'
tagline: A brand new course on Learning Lab
description: ' In this course, we''ll take a look at examples of what makes a good presenter,and use these examples to show what small changes you can make to your presenting style to stand out from the crowd.'
template:
  repo: course-1-what-makes-a-good-public-speaker-template
  name: course-1-what-makes-a-good-public-speaker
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
